apiVersion: v1
kind: Service
metadata:
  name: debug
  namespace: expense
spec:
  selector:
    component: debug
    project: expense
    tier: debug
  ports:
  - protocol: TCP
    port: 81 #service-port
    targetPort: 81 #target-port
